multiplex:
    1:
        layers:
            - multiplex/1/Complexes_gene_names_190123.gr
            - multiplex/1/Pathways_reactome_gene_names_190123.gr
            - multiplex/1/PPI_HiUnion_LitBM_APID_gene_names_190123.gr
    2:
        layers:
            - multiplex/2/RareDiseasePathways_network_useCase1.gr
bipartite:
    bipartite/Bipartite_RareDiseasePathways_geneSymbols_useCase1.gr:
        source: 2
        target: 1
seed:
    seeds.txt
