multiplex:
    1:
        layers:
            - multiplex/1/Complexes_Nov2020.gr
            - multiplex/1/PPI_Jan2021.gr
            - multiplex/1/Reactome_Nov2020.gr
    2:
        layers:
            - multiplex/2/pathwaysOfInterestNetwork_fromPaper.sif
bipartite:
    bipartite/Bipartite_pathOfInterest_geneSymbols_fromPaper.tsv:
        source: 2
        target: 1
seed:
   seeds.txt
