multiplex:
    1:
        layers:
            - multiplex/1/Complexes_Nov2020.gr
            - multiplex/1/PPI_Jan2021.gr
            - multiplex/1/Reactome_Nov2020.gr
    2:
        layers:
            - multiplex/2/WP_RareDiseasesNetwork_fromVitaminPaper.sif
bipartite:
    bipartite/Bipartite_WP_RareDiseases_geneSymbols_fromVitaminPaper.tsv:
        source: 2
        target: 1
seed:
    /home/morgane/Documents/05_EJPR_RD/WF_Environment/EnvironmentProject/examples/InputData/seeds.txt
